title: Dev.KDH - 개발 블로그
author: Kwon.Dohan
email: andong_kdh@naver.com
description: > # this means to ignore newlines until "show_exerpts:"
  어느 중학생의 개발 블로그!!
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: /

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Kwon.Dohan
  tagline: Developer | Programer | Designer
  date_format: "%Y.%b-%-d"
  style: black
  showNav: true
  showPicker: false
  navigation:
    - title: Dev Blog
      url: "/"
    - title: About Me
      url: "http://www.kdh0604.kro.kr/"
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
